# Generated by Django 5.2.5 on 2025-08-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passagesharer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
