# Generated by Django 5.2.5 on 2025-08-28 03:21

from django.db import migrations, models

def save_old_author_data(apps, schema_editor):
    Passage = apps.get_model('passagesharer', 'Passage')
    
    for passage in Passage.objects.all():
        passage.old_author = passage.author
        passage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('passagesharer', '0002_passage_last_updated_at'),
    ]

    operations = [
        migrations.RunPython(save_old_author_data),
    ]
