# Generated by Django 5.2.5 on 2025-08-28 04:41

from django.db import migrations, models


def save_old_author_data(apps, schema_editor):
    Passage = apps.get_model('passagesharer', 'Passage')
    
    for passage in Passage.objects.all():
        passage.old_author = passage.author
        passage.save()



class Migration(migrations.Migration):

    dependencies = [
        ('passagesharer', '0003_add_old_author_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='old_author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(save_old_author_data)
    ]
