# Generated by Django 5.2.5 on 2025-08-28 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def convert_author_to_foreignkey(apps, schema_editor):
    Passage = apps.get_model('passagesharer', 'Passage')
    User = apps.get_model('auth', 'User')
    
    for passage in Passage.objects.all():
        try:
            user = User.objects.get(username=passage.old_author)
            passage.author = user
            passage.save()
        except User.DoesNotExist:
            admin_user = User.objects.get(username='admin')
            passage.author = admin_user
            passage.save()

class Migration(migrations.Migration):

    dependencies = [
        ('passagesharer', '0004_passage_old_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(convert_author_to_foreignkey)
    ]
