# Generated by Django 5.2.5 on 2025-08-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passagesharer', '0005_alter_passage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='old_author',
        ),
    ]
